ARG NODE_VERSION=22.14.0
ARG ALPINE_VERSION=3.21

FROM node:${NODE_VERSION}-alpine AS node

FROM alpine:${ALPINE_VERSION}

FROM mcr.microsoft.com/devcontainers/base:alpine-3.21

COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

WORKDIR /workspace

COPY package*.json ./

RUN npm install

EXPOSE 80

CMD ["npm", "run", "dev", "--", "--port=80"]
