services:
  task-runner:
    build: ./task-runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONFIG_PATH=$(pwd)/config
      - DEBUG=1
    depends_on:
      - registry
    develop:
      watch:
        - action: rebuild
          path: ./task-runner
          target: /app

  registry:
    image: registry:2
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: package.json
    restart: unless-stopped
    ports:
      - "3000:80"
