# This is for development puposes only

services:
  test-worker:
    build: ./task-runner/analysis
    entrypoint: /bin/bash test.sh

  task-runner:
    build: ./task-runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - registry

  registry:
    image: registry:2
    restart: unless-stopped

  frontend:
    build: ./frontend
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: package.json
    ports:
      - "3000:3000"
    volumes:
      - /app/.next
