services:
  preset-db:
    build: ./preset-db
    restart: no
    develop:
      watch:
        - action: sync+restart
          path: ./db
          target: /app
        - action: rebuild
          path: ./db/package.json

  reverse-proxy:
    image: nginx:latest
    restart: no
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    develop:
      watch:
        - action: rebuild
          path: ./nginx.conf

  task-runner:
    build: ./task-runner
    restart: no
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    develop:
      watch:
        - action: sync+restart
          path: ./task-runner
          target: /app
        - action: rebuild
          path: ./task-runner/package.json

  # we just need it to be built, not run
  # it will error because there's no command
  analysis-tool:
    build: ./analysis-tool
    network_mode: "none" # restriction for analysis tool
    entrypoint: /bin/bash -c "while true; do sleep 1000; done" # we want it to be built, every time we change the code, but we don't want it to run
    develop:
      watch:
        - action: rebuild
          path: ./analysis-tool

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/package.json
    restart: no