services:
  preset-db:
    build: ./db
    restart: unless-stopped
    develop:
      watch:
        - action: sync+restart
          path: ./db
          target: /app
        - action: rebuild
          path: ./db/package.json

  reverse-proxy:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    develop:
      watch:
        - action: rebuild
          path: ./nginx.conf

  task-runner:
    build: ./task-runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3001:80"
    environment:
      - DEBUG=1
    develop:
      watch:
        - action: rebuild
          path: ./task-runner
          target: /app

  # we just need it to be built, not run
  # it will error because there's no command
  analysis-tool:
    build: ./analysis-tool
    restart: no # because we just want it to be build
    # entrypoint: ['/bin/bash', '-c', 'echo rebuild is done']
    # command: []
    command: ['noop']
    develop:
      watch:
        - action: rebuild
          path: ./analysis-tool

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: package.json
    restart: unless-stopped
