# This is for development puposes only

services:

  task-queue:
    image: rabbitmq:3
    restart: unless-stopped

  task-runner:
    build: ./task-runner

  frontend:
    build: ./frontend
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: package.json
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - /app/.next
    # depends_on:
    #   - backend