services:
  preset-db:
    build: ./preset-db
    restart: unless-stopped

  reverse-proxy:
    build: ./reverse-proxy
    restart: unless-stopped
    ports:
      - "$PORT:80"

  executor:
    build: ./executor
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env

  # we just need it to be built, not run
  # it will error because there's no command
  analysis-tool:
    build: ./analysis-tool
    entrypoint: /bin/bash -c "echo it's ok for me to be stopped :)" # we want it to be built, but we don't want it to be run

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: unless-stopped