# This is for development puposes only

services:
  task-runner:
    build: ./task-runner
    restart: unless-stopped
    # privileged: true
    volumes:
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build: ./frontend
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: package.json
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - /app/.next
