services:
  preset-db:
    build: ./preset-db
    restart: unless-stopped

  reverse-proxy:
    build: ./reverse-proxy
    restart: unless-stopped
    ports:
      - "$PORT:80"

  executor:
    build: ./executor
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: unless-stopped