services:
  preset-db:
    build: ./preset-db
    restart: no
    develop:
      watch:
        - action: sync+restart
          path: ./preset-db
          target: /app
        - action: rebuild
          path: ./preset-db/package.json

  reverse-proxy:
    build: ./reverse-proxy
    restart: no
    ports:
      - "$PORT:80"
    develop:
      watch:
        - action: sync+restart
          path: ./nginx.conf
          target: /etc/nginx/nginx.conf

  executor:
    build: ./executor
    restart: no
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    develop:
      watch:
        - action: sync+restart
          path: ./executor
          target: /app
        - action: rebuild
          path: ./executor/package.json

  # we just need it to be built, not run
  # it will error because there's no command
  analysis-tool:
    build: ./analysis-tool
    entrypoint: /bin/bash -c "while true; do sleep 1000; done" # we want it to be built, every time we change the code, but we don't want it to run
    develop:
      watch:
        - action: rebuild
          path: ./analysis-tool

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/package.json
    restart: no